language: php

php:
  - "5.4"
  - "5.3"

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

matrix:
  allow_failures:
    - php: 5.4

before_script:
  # Setup for Selenium tests
  #- export DISPLAY=:99
  #- export WEB_FIXTURES_HOST=http://localhost
  #- export WEB_FIXTURES_BROWSER=firefox

  # Selenium first, give it time to boot..
  #- wget http://selenium.googlecode.com/files/selenium-server-standalone-2.28.0.jar
  #- java -jar selenium-server-standalone-2.28.0.jar > /dev/null &

  # Install dependencies
  #- sudo apt-get update
  #- sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-mysql
  #- sudo sed -i -e "s,/var/www,$(pwd)/wolfcms/tests/selenium,g" /etc/apache2/sites-available/default
  #- sudo /etc/init.d/apache2 restart
  
  # Install Wolf CMS files
  # todo
  
  # Setup rights for Wolf CMS files

  # Start up graphics
  #- sh -e /etc/init.d/xvfb start

  #- sleep 5
  
  # Run Wolf CMS Installer using Selenium
  #- sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS wolfcms_selenium;' -U postgres; fi"
  #- sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database wolfcms_selenium;' -U postgres; fi"
  #- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS wolfcms_selenium;'; fi"
  #- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database wolfcms_selenium;'; fi"
  # todo
  
  # Change admin password in DB
  #- sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'UPDATE wolfcms_selenium SET password='TBD',salt='TDB' WHERE username=admin;' -U postgres; fi"
  #- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'UPDATE wolfcms_selenium SET password='TBD',salt='TDB' WHERE username=admin;'; fi"

  # Run PHPUnit tests...
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS wolfcms_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database wolfcms_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS wolfcms_test;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database wolfcms_test;'; fi"
  - git clone --depth=100 --quiet git://github.com/wolfcms/wolfcms-phpunit.git test
  - cd test

script: phpunit --configuration phpunit.travisci.xml
